DDCYLS-3147: Proof of concept work
hmrc/digital-disclosure-service-journey-tests pull request #108
Opened 2023-08-02 12:56 UTC by ellie-l-newell

2023-08-08 14:46 UTC, lewishay requested changes

2023-08-10 08:35 UTC, lewishay requested changes

2023-08-10 08:35 UTC, lewishay commented on src/test/scala/uk/gov/hmrc/utils/TestConfiguration.scala
> +      case "UsingThisServiceUrl"             => baseUrl("dds") + "using-this-service"
Apologies for the late comment but I've been having a chat with Mike regarding his current AMLS AT PR and we think that we can make a change to this sort of String matching. Essentially we want to remove the need to have "Url" suffix on the end of these. Can you reach out to him to understand what he's going to do for this so we can keep it consistent.

2023-08-15 07:59 UTC, ellie-l-newell commented on src/test/scala/uk/gov/hmrc/stepdefs/CaseManagementStepDef.scala
> +    urlVerify(prettyUrl)
The URL is being checked after 'continue' is clicked to confirm it has navigated to the correct page

2023-08-21 14:28 UTC, jpatton638 commented on src/test/scala/uk/gov/hmrc/pages/BasePage.scala
> +  chromeOptions.setBinary("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome")
This looks like it would only work on MacOS, so this might need changing

2023-08-21 14:28 UTC, jpatton638 commented on src/test/scala/uk/gov/hmrc/stepdefs/Hooks.scala
> +//  @After
Can you remove this please?

2023-08-22 08:52 UTC, jpatton638 submitted a review, later dismissed

2023-08-22 09:12 UTC, lewishay requested changes

2023-08-22 09:12 UTC, lewishay commented on run_browser_with_docker.sh
> +port_mappings=$(sm2 --status | grep PASS | awk '{ print $8"->"$8 }' | paste -sd "," -)
This command doesn't seem to grab the ports any more. You can test it by pasting it into terminal; it should give you the open ports of SM services with an arrow in between, separated by commas, e.g. `1234->1234,5678->5678`

Seems like the previous command was fine?

2023-08-22 09:24 UTC, lewishay approved these changes

2023-08-22 09:24 UTC, merged